# https://hub.docker.com/r/jonnyan404/anytls
services:
  app:
    image: jonnyan404/anytls:latest
    restart: always
    container_name: anytls-server
    ports:
      - ${PORT:-9443}:${PORT:-9443}
    environment:
      TZ: ${TZ:-Etc/UTC}
      MIMA: ${MIMA}
      PORT: ${PORT:-9443}
    networks:
      - network
networks:
  network:
    enable_ipv6: true
