services:
  suwayomi:
    image: ghcr.io/suwayomi/tachidesk:latest
    container_name: suwayomi
    restart: on-failure:3
    environment:
      - TZ=${TZ:-Etc/UTC}
      - DATABASE_TYPE=POSTGRESQL
      - DATABASE_URL=postgresql://${POSTGRES_HOST:-postgresql}:${POSTGRES_PORT:-5432}/${POSTGRES_DB}
      - DATABASE_USERNAME=${POSTGRES_USER}
      - DATABASE_PASSWORD=${POSTGRES_PASSWORD}
      - FLARESOLVERR_ENABLED=true
      - FLARESOLVERR_URL=http://flaresolverr:8191
      - EXTENSION_REPOS=["https://raw.githubusercontent.com/keiyoushi/extensions/repo/index.min.json"]
    depends_on:
      postgresql:
        condition: service_healthy
        restart: true
    ports:
      - 4567:4567
    volumes:
      - ./data:/home/suwayomi/.local/share/Tachidesk
      - ${SUWAYOMI_LOCAL_DIR:-./data/local}:/home/suwayomi/.local/share/Tachidesk/local
      - ${SUWAYOMI_BACKUPS_DIR:-./data/backups}:/home/suwayomi/.local/share/Tachidesk/backups
    # user: 1000:1000
    networks:
      - postgresql
      - flaresolverr
      - suwayomi
  postgresql:
    image: docker.io/postgres:latest
    container_name: postgresql
    restart: always
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - PGDATA=/data/postgres
      - TZ=${TZ:-Etc/UTC}
      - PGTZ=${TZ:-Etc/UTC}
    expose:
      - 5432
    ports:
      - ${POSTGRES_PORT:-5432}:5432
    volumes:
      - ./postgres:/data/postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - postgresql
  flaresolverr:
    image: ghcr.io/thephaseless/byparr:latest
    container_name: flaresolverr
    restart: always
    expose:
      - 8191
    init: true
    environment:
      - TZ=${TZ:-Etc/UTC}
    networks:
      - flaresolverr
networks:
  postgresql: {}
  flaresolverr: {}
  suwayomi: {}
