services:
  app:
    volumes:
      - ${SUWAYOMI_LOCAL_DIR:-./data/local}:/home/suwayomi/.local/share/Tachidesk/local
      - ${SUWAYOMI_BACKUPS_DIR:-./data/backups}:/home/suwayomi/.local/share/Tachidesk/backups
      - ${SUWAYOMI_EXTENSIONS_DIR:-./data/extensions}:/home/suwayomi/.local/share/Tachidesk/extensions
