# https://github.com/Suwayomi/Suwayomi-Server-docker
services:
  app:
    image: ghcr.io/suwayomi/tachidesk:preview
    restart: on-failure:3
    environment:
      TZ: ${TZ:-Etc/UTC}
      DATABASE_TYPE: POSTGRESQL
      DATABASE_URL: postgresql://${POSTGRES_HOST:-db}:${POSTGRES_PORT:-5432}/${POSTGRES_DB:-suwayomi}
      DATABASE_USERNAME: ${POSTGRES_USER}
      DATABASE_PASSWORD: ${POSTGRES_PASSWORD}
      AUTH_MODE: ${SUWAYOMI_AUTH_MODE:-none}
      AUTH_USERNAME: ${SUWAYOMI_AUTH_USERNAME}
      AUTH_PASSWORD: ${SUWAYOMI_AUTH_PASSWORD}
      FLARESOLVERR_ENABLED: true
      FLARESOLVERR_URL: http://flaresolverr:8191
      EXTENSION_REPOS: '["https://raw.githubusercontent.com/keiyoushi/extensions/repo/index.min.json"]'
    depends_on:
      db:
        condition: service_healthy
        restart: true
    ports:
      - 4567:4567
    volumes:
      - ./data:/home/suwayomi/.local/share/Tachidesk
    # user: 1000:1000
    networks:
      - network
  db:
    image: docker.io/library/postgres:latest
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-suwayomi}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /data/postgres
      TZ: ${TZ:-Etc/UTC}
      PGTZ: ${TZ:-Etc/UTC}
    expose:
      - 5432
    volumes:
      - ./postgres:/data/postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - network
  flaresolverr:
    image: ghcr.io/thephaseless/byparr:latest
    restart: always
    expose:
      - 8191
    init: true
    environment:
      TZ: ${TZ:-Etc/UTC}
    networks:
      - network
networks:
  network:
    enable_ipv6: true
